name: CI

on:
  push:
    branches:
      - main
# schedule:
#   - cron:  '0 02 * * *'
#   - cron:  '0 08 * * *'
#   - cron:  '0 14 * * *'
#   - cron:  '0 20 * * *'

jobs:
  download-dwd-icon:
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: ownload-remap-upload
      run: |
        sudo apt-get update
        sudo apt-get -y install cdo

        dotnet run -- download-remap-upload --cdo-path $(which cdo)

